version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    networks:
      - mern-network
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  server:
    build: ./server
    container_name: server
    networks:
      - mern-network
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/mern-app
      - PORT=5000
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: client
    networks:
      - mern-network
    ports:
      - "3000:3000"
    
    depends_on:
      - server
      
networks:
  mern-network:
    driver: bridge 

volumes:
  mongodb_data:
    driver: local

    